import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect, useRef, useState} from "react";
import swap from "../util/swap";
import regenerate from "../util/regenerate";
import {HEAP, isSorted} from "../util/helperMethods";
import {setAllGreen} from "../util/animationHelperMethods";
import Sort from "../components/Sort";

export default function Home() {
    // Variables
    const [numberRectangles, setNumberRectangles] = useState(27)
    const [delay, setDelay] = useState(500)
    const [arr, setArr] = useState([])
    const [active, setActive] = useState(false)
    const delayRef = useRef()
    delayRef.current = delay


    // Regenerating rectangles
    useEffect(() => {
        regenerate(active, numberRectangles, setArr)
    }, [numberRectangles])

    let heapify = async (n, i) => {
        let largest = i
        let left = 2 * i + 1
        let right = 2 * i + 2

        if (left < n && arr[left].props.height > arr[largest].props.height) {
            await swap(left, largest, arr, setArr, delayRef, false);
            largest = left
        }

        if (right < n && arr[right].props.height > arr[largest].props.height) {
            await swap(right, largest, arr, setArr, delayRef, false);
            largest = right
        }

        if (largest !== i) {
            await swap(i, largest, arr, setArr, delayRef,true)
            await heapify(n, largest)
        }
    }

    let heapSort = async () => {
        if (isSorted(arr) || active) {
            setAllGreen(arr, setArr)
            return
        }

        setActive(true)
        for (let i = Math.floor(arr.length / 2) - 1; i >= 0; i--) {
            await heapify(arr.length, i)
        }

        for (let i = arr.length - 1; i > 0; i--) {
            await swap(0, i, arr, setArr, delayRef, true, HEAP)
            await heapify(i, 0)
        }
        setAllGreen(arr, setArr)
        setActive(false)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Quick Sort Visualizer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Sort
                setNumberRectangles={setNumberRectangles}
                setDelay={setDelay}
                active={active}
                numberRectangles={numberRectangles}
                arr={arr}
                setArr={setArr}
                sortingMethod={heapSort}
            />
        </div>
    )
}
