import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorting Algorithm Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Nick&apos;s<br/>
          <a href="https://github.com/nhulston" target="_blank" rel="noreferrer">Algorithm Visualizer</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/bubblesort" className={styles.card}>
            <h2>Bubble Sort &rarr;</h2>
            <p>The simplest sorting algorithm with very high time complexity.</p>
          </a>

          <a href="/mergesort" className={styles.card}>
            <h2>Merge Sort &rarr;</h2>
            <p>A recursive algorithm that sorts two halves, then merges the two halves.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Heap Sort &rarr;</h2>
            <p>Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum </p>
          </a>

          <a
            href="/quicksort"
            className={styles.card}
          >
            <h2>Quick Sort &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
          </span>
        </a>
      </footer>
    </div>
  )
}
