import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect, useRef, useState} from "react";
import swap from "../util/swap";
import regenerate from "../util/regenerate";
import {isSorted, SELECTION} from "../util/helperMethods";
import {setAllGreen} from "../util/animationHelperMethods";
import Sort from "../components/Sort";

export default function Home() {
    // Variables
    const [numberRectangles, setNumberRectangles] = useState(27)
    const [delay, setDelay] = useState(500)
    const [arr, setArr] = useState([])
    const [active, setActive] = useState(false)
    const delayRef = useRef()
    delayRef.current = delay


    // Regenerating rectangles
    useEffect(() => {
        regenerate(active, numberRectangles, setArr)
    }, [numberRectangles])


    let selectionSort = async () => {
        if (isSorted(arr) || active) {
            setAllGreen(arr, setArr)
            return
        }

        setActive(true)

        for (let i = 0; i < arr.length - 1; i++) {
            let minIndex = i
            for (let j = i + 1; j < arr.length; j++) {
                await swap(j, minIndex, arr, setArr, delayRef)
                if (arr[j].props.height < arr[minIndex].props.height) {
                    minIndex = j
                }
            }
            await swap(i, minIndex, arr, setArr, delayRef, true, SELECTION)
        }

        setAllGreen(arr, setArr)
        setActive(false)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Quick Sort Visualizer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Sort
                setNumberRectangles={setNumberRectangles}
                setDelay={setDelay}
                active={active}
                numberRectangles={numberRectangles}
                arr={arr}
                setArr={setArr}
                sortingMethod={selectionSort}
            />
        </div>
    )
}
